# basic
title: TechBridge 技術共筆部落格
subtitle: var topics = ['Web前後端', '行動網路', '機器人/物聯網', '數據分析', '產品設計', 'etc.'];
shareTitle: 追蹤 TechBridge 技術日報，技術資訊分享不漏接！
bio: TechBridge Weekly 技術週刊團隊是一群對用技術改變世界懷抱熱情的團隊。本技術共筆部落格初期專注於Web前後端、行動網路、機器人/物聯網、數據分析與產品設計等技術分享。This is TechBridge Weekly Team Tech Blog, which focus on web, mobile, robot, IoT, data analytics technology sharing.
favicon: /img/logo-tb-500-500.png
logo: /img/logo-tb-500-500.png

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: /img/logo-tb-500-500.png
banner_small: /img/cover-small.jpg
banner_large: /img/cover-small.jpg

# disqus
disqus_shortname: techbridgeweekly

# Content
excerpt_link: Read More

# social
social:
  github: https://github.com/TechBridgeHQ
  twitter: https://twitter.com/techbridgecc
  facebook: http://www.facebook.com/TechBridgeTW

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
